### ISSUE TITLE
Stateful allocators in datasketches-cpp

### ISSUE THREAD

**Issue by jmalkin** [criteo/vertica-datasketch#3]
The datasketches-cpp team noticed your comment about allocators in the library. We're certainly willing to look at this, but don't (yet) have a lot of experience with them. We've opened an issue to support that use case, but we also have a question.

First, the issue in our repo (and feel free to reply there): https://github.com/apache/incubator-datasketches-cpp/issues/160

It seems like it won't be too hard to allow a pre-instantiated allocator to be passed in and to support operations within the same allocator. But would it be a requirement to support things like copy/move/assignment between different allocator instances? That seems likely to require more research on our end to support.

**Comment by alexandre-p** [comment]
Hello,
Thank you very much for considering our use case !

What we need is just to be able to choose are own allocator implementation. I think having the STL allocator by default would make sense and work for most of the datasketches-cpp users.

But in our case we would like to set a custom Vertica allocator (to be able to rely on Vertica memory constraint and management natively).

At this stage, I can't say we need support for operations between allocators.

Thanks,
Alexandre for Criteo

**Comment by jmalkin** [comment]
Finally have an update on this. We recently added the tuple sketch to the repo (not yet released; we'd like a bit more testing) which does support stateful allocators. And there's a specialization of the tuple sketch to have no summary, meaning it's identical to a theta sketch. We're currently calling that theta_sketch_experimental, and it's in the /tuple folder.

We believe that will work for your use case. It's a tiny bit slower than the original theta sketch, but it really is a fairly small difference. If you have a chance, please check it out and let us know if it works for you.

**Comment by AlexanderSaydakov** [comment]
@alexandre-p Could you point me to the allocator you would like to use? Thank you.

**Comment by jmalkin** [comment]
We haven't yet done a release, but this has been resolved in all c++ sketches.
